image: nexus-docker-hub.south.rt.ru/library/node:14.18.0

stages:
  - install
  - publish

variables:
  APP_NAME: stylekit-molecules
  APP_DEVELOPER: Viktor.Sidorets
  APP_LANG: NodeJS
  APP_LANG_VERSION: "14.18.0"
  APP_PROJECT: rtru

  GIT_SUBMODULE_STRATEGY: normal

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour
  only:
    - RTRU-12171-2

nexus:
  stage: publish
  script:
    - node ./prepublish.cjs
    - npm run build
    - node ./nexus-login.cjs
    - npm publish
  only:
    - RTRU-12171-2
