// as Name directive for initialization
export { default as GaClick } from './GaClick'
export { default as PopupTrigger } from '../components/Popup/PopupTrigger'
export { default as RtOutSideClick } from './OutsideClick/OutsideClick'
export { default as RtResizeContentHeight } from './ResizeContentHeight'
export { default as RtScrollToOnClick } from './ScrollToOnClick/ScrollToOnClick'
export { default as RtSlideContentVertical } from './SlideContent/SlideContentVertical'
export { SwipeRight as RtSwipeRight } from './Swipe/swipe'
export { SwipeLeft as RtSwipeLeft } from './Swipe/swipe'
export { default as Tooltip } from './Tooltip/tooltip'
